{% set python_min = "3.10" %}
{% set name = "gordias" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gordias-{{ version }}.tar.gz
  sha256: a09a9b60812a9cd9add36e25726f4e9d238b777716fc1f11455fd199c0bf4d3e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=77
    - wheel
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - cftime
    - cf-units
    - dask >=2023.1.0
    - dask-jobqueue
    - dask-mpi
    - distributed >=2023.1.0
    - isodate
    - netcdf4
    - numpy
    - pandas
    - psutil
    - iris >=3,<4

test:
  requires:
    - python {{ python_min }}
  imports:
    - gordias

about:
  home: https://git.smhi.se/climix/gordias
  summary: A core project for climate data handling
  dev_url: https://git.smhi.se/climix/gordias
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nCarolina
    - ljoakim
