{% set name = "gordias" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gordias-{{ version }}.tar.gz
  sha256: b8a4348a243fdccac68793557515c82812d85ade9200867c9d7973fd4557bea0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=64
    - wheel
    - setuptools-scm >=8
    - pip
  run:
    - python >=3.10
    - cftime
    - cf-units
    - dask >=2023.1.0
    - dask-jobqueue
    - dask-mpi
    - distributed >=2023.1.0
    - isodate
    - netcdf4
    - numpy <2
    - pandas
    - psutil
    - iris >=3,<4

test:
  imports:
    - gordias

about:
  home: https://git.smhi.se/climix/gordias
  summary: A core project for climate data handling
  dev_url: https://git.smhi.se/climix/gordias
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nCarolina
    - ljoakim
