{% set python_min = '3.10' %}
{% set name = "gordias" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gordias-{{ version }}.tar.gz
  sha256: f663262f37032aa2fc3b7b4259fc89436ffbbf1d526189974cf74c42ce890ed2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - wheel
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - cftime
    - cf-units
    - dask >=2023.1.0
    - dask-jobqueue
    - dask-mpi
    - distributed >=2023.1.0
    - isodate
    - netcdf4
    - numpy
    - pandas
    - psutil
    - iris >=3,<4

test:
  requires:
    - python {{ python_min }}
  imports:
    - gordias

about:
  home: https://git.smhi.se/climix/gordias
  summary: A core project for climate data handling
  dev_url: https://git.smhi.se/climix/gordias
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nCarolina
    - ljoakim
